CreateRuleException in line 216 of /shared/liuhj/tonglv/ICU_tonglv_scripts/iSNV_calling_bwa2_AE004091.2/iSNV_calling-pipeline.py:
The name iSNV_snvNumCount is already used by another rule
  File "/shared/liuhj/tonglv/ICU_tonglv_scripts/iSNV_calling_bwa2_AE004091.2/iSNV_calling-pipeline.py", line 216, in <module>
